mysql:
  image: mysql:8
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=root
    - MYSQL_PASSWORD=root
    - MYSQL_DATABASE=medicalclinic
  volumes:
    - "./conf.d:/etc/mysql/conf.d:ro"
